/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ViewDetails;

import Business.WorkQueue.BankLoanWorkRequest;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class BankWRViewJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private BankLoanWorkRequest request;
    public BankWRViewJPanel(JPanel userProcessContainer,BankLoanWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        populateDetails(request);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loanAmountJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        agricultureLandAddJTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        loanReasonJTextField1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        emailIdJTextField = new javax.swing.JTextField();
        annualIncomeJTextField = new javax.swing.JTextField();
        panCardPathJTextField = new javax.swing.JTextField();
        valueOfAgricultureLandJTextField = new javax.swing.JTextField();
        landUploadjButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        phoneNoJTextField1 = new javax.swing.JTextField();
        panUploadjButton1 = new javax.swing.JButton();
        bankNamejTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, 50));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 237, -1, -1));

        nameJTextField.setEditable(false);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 229, 155, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 273, -1, -1));

        ageJTextField.setEditable(false);
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 269, 155, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 309, -1, -1));

        addressJTextField.setEditable(false);
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 297, 155, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bank Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 345, -1, -1));

        jLabel6.setText("Loan Amount");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 229, -1, -1));

        loanAmountJTextField.setEditable(false);
        add(loanAmountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 223, 187, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SSN Doc");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 487, -1, -1));

        agricultureLandAddJTextField.setEditable(false);
        add(agricultureLandAddJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 325, 187, -1));

        jLabel8.setText("Reason for Loan");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 260, -1, -1));

        loanReasonJTextField1.setEditable(false);
        add(loanReasonJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 257, 187, -1));

        jLabel9.setText("Annual Income");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 294, -1, -1));

        jLabel10.setText("Collateral Details");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 331, -1, -1));

        jLabel11.setText("Collateral Document");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 368, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email Id");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 394, -1, -1));

        emailIdJTextField.setEditable(false);
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 391, 155, -1));

        annualIncomeJTextField.setEditable(false);
        add(annualIncomeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 291, 187, -1));

        panCardPathJTextField.setEditable(false);
        add(panCardPathJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 484, 155, -1));

        valueOfAgricultureLandJTextField.setEditable(false);
        add(valueOfAgricultureLandJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(747, 362, 187, -1));

        landUploadjButton.setBackground(new java.awt.Color(0, 0, 0));
        landUploadjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        landUploadjButton.setForeground(new java.awt.Color(255, 255, 255));
        landUploadjButton.setText("View");
        landUploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                landUploadjButtonActionPerformed(evt);
            }
        });
        add(landUploadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(844, 402, 90, 40));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone No.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 434, -1, -1));

        phoneNoJTextField1.setEditable(false);
        add(phoneNoJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 431, 155, -1));

        panUploadjButton1.setBackground(new java.awt.Color(0, 0, 0));
        panUploadjButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panUploadjButton1.setForeground(new java.awt.Color(255, 255, 255));
        panUploadjButton1.setText("View");
        panUploadjButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUploadjButton1ActionPerformed(evt);
            }
        });
        add(panUploadjButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 530, 80, 40));

        bankNamejTextField1.setEditable(false);
        add(bankNamejTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 335, 155, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel15.setText("Bank work request View details");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 530, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bankbg.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateDetails(BankLoanWorkRequest request)
    {
        ageJTextField.setText(String.valueOf(request.getAge()));
        addressJTextField.setText(request.getAddress());
        bankNamejTextField1.setText(request.getBankName());
        loanAmountJTextField.setText(String.valueOf(request.getLoanAmount()));
        loanReasonJTextField1.setText(request.getCollateral());
        annualIncomeJTextField.setText(String.valueOf(request.getAnnualIncome()));
        agricultureLandAddJTextField.setText(request.getCollateral());
        valueOfAgricultureLandJTextField.setText(request.getCollateralValue());
        emailIdJTextField.setText(request.getEmailId());
        phoneNoJTextField1.setText(String.valueOf(request.getPhoneNo()));
        panCardPathJTextField.setText(request.getSSNPath());
        nameJTextField.setText(request.getName());
    }
    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void landUploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_landUploadjButtonActionPerformed
        // TODO add your handling code here:
        File f = new File(request.getCollateralValue());
        File file = f.getAbsoluteFile();
          try{
          Desktop.getDesktop().open(file);
          }catch(Exception ex){
              System.out.println("Exception"+ex);
          }
    }//GEN-LAST:event_landUploadjButtonActionPerformed

    private void panUploadjButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUploadjButton1ActionPerformed
        // TODO add your handling code here:
        File f = new File(request.getSSNPath());
        File file = f.getAbsoluteFile();
          try{
          Desktop.getDesktop().open(file);
          }catch(Exception ex){
              System.out.println("Exception"+ex);
          }
    }//GEN-LAST:event_panUploadjButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JTextField agricultureLandAddJTextField;
    private javax.swing.JTextField annualIncomeJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bankNamejTextField1;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton landUploadjButton;
    private javax.swing.JTextField loanAmountJTextField;
    private javax.swing.JTextField loanReasonJTextField1;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JTextField panCardPathJTextField;
    private javax.swing.JButton panUploadjButton1;
    private javax.swing.JTextField phoneNoJTextField1;
    private javax.swing.JTextField valueOfAgricultureLandJTextField;
    // End of variables declaration//GEN-END:variables
}
