/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.ViewDetails;

import Business.WorkQueue.SubsidyWorkRequest;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.File;
import javax.swing.JPanel;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class SubsidyWRViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SubsidyWRViewJPanel
     */
    private JPanel userProcessContainer;
    private SubsidyWorkRequest request;
    public SubsidyWRViewJPanel(JPanel userProcessContainer, SubsidyWorkRequest request) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.request=request;
        populateDetails(request);
    }
    
    private void populateDetails(SubsidyWorkRequest request)
    {
        nameJTextField.setText(request.getName());
        ageJTextField.setText(String.valueOf(request.getAge()));
        addressJTextField.setText(request.getAddress());
        bankNameJTextField.setText(request.getBankName());
        expectedIncomeJTextField.setText(String.valueOf(request.getExpectedIncome()));
        actualIncomeJTextField.setText(String.valueOf(request.getActualIncome()));
        emailIdJTextField.setText(request.getEmailId());
        phoneNoJTextField1.setText(String.valueOf(request.getPhoneNo()));
        ssnPathJTextField.setText(request.getProofPath());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backJButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        expectedIncomeJTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        actualIncomeJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailIdJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phoneNoJTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ssnPathJTextField = new javax.swing.JTextField();
        panUploadjButton = new javax.swing.JButton();
        bankNameJTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 50, 90, 40));

        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 208, -1, -1));

        nameJTextField.setEditable(false);
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 205, 400, -1));

        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 244, -1, -1));

        ageJTextField.setEditable(false);
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 241, 397, -1));

        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 280, -1, -1));

        addressJTextField.setEditable(false);
        addressJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressJTextFieldActionPerformed(evt);
            }
        });
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 277, 397, -1));

        jLabel5.setText("Bank Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 313, -1, -1));

        jLabel6.setText("Expected Income");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 349, -1, -1));

        expectedIncomeJTextField.setEditable(false);
        add(expectedIncomeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 349, 397, -1));

        jLabel7.setText("Actual Income");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 385, -1, -1));

        actualIncomeJTextField.setEditable(false);
        add(actualIncomeJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 385, 400, -1));

        jLabel12.setText("Email Id");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 419, -1, -1));

        emailIdJTextField.setEditable(false);
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 419, 394, -1));

        jLabel13.setText("Phone No.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 456, -1, -1));

        phoneNoJTextField1.setEditable(false);
        add(phoneNoJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 453, 394, -1));

        jLabel8.setText("Proof of Income");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 493, -1, -1));

        ssnPathJTextField.setEditable(false);
        add(ssnPathJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 493, 394, -1));

        panUploadjButton.setBackground(new java.awt.Color(0, 0, 0));
        panUploadjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        panUploadjButton.setForeground(new java.awt.Color(255, 255, 255));
        panUploadjButton.setText("View");
        panUploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUploadjButtonActionPerformed(evt);
            }
        });
        add(panUploadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(672, 530, 100, 50));

        bankNameJTextField.setEditable(false);
        add(bankNameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 310, 397, -1));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel15.setText("Government subsidy Request View details");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 854, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/govt_image.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 850));
    }// </editor-fold>//GEN-END:initComponents

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backJButtonActionPerformed

    private void panUploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUploadjButtonActionPerformed
        // TODO add your handling code here:
        File f = new File(request.getProofPath());
        File file = f.getAbsoluteFile();
          try{
          Desktop.getDesktop().open(file);
          }catch(Exception ex){
              System.out.println("Exception"+ex);
          }
    }//GEN-LAST:event_panUploadjButtonActionPerformed

    private void addressJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressJTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actualIncomeJTextField;
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField bankNameJTextField;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JTextField expectedIncomeJTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton panUploadjButton;
    private javax.swing.JTextField phoneNoJTextField1;
    private javax.swing.JTextField ssnPathJTextField;
    // End of variables declaration//GEN-END:variables
}
