/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnergyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.EnergyOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BankLoanWorkRequest;
import Business.WorkQueue.EquipmentWorkRequest;
import Business.WorkQueue.MaterialWorkRequest;
import Business.WorkQueue.MicroLoanWorkRequest;
import Business.WorkQueue.ElectricityWorkRequest;
import Business.WorkQueue.SubsidyWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class EnergyWorkAreaJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private EnergyOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;

    public EnergyWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, EnergyOrganization organization, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system =system;
        valueLabel.setText(enterprise.getName());
        createTabs();
    }
    
     public void createTabs() {
        ViewLoanRequestsJPanel loanStatus=new ViewLoanRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Loan Status",loanStatus);
        ViewMicroLoanRequestsJPanel microLoanStatus=new ViewMicroLoanRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Micro Loan Status",microLoanStatus);
        ViewOrderRequestsJPanel orderStatus=new ViewOrderRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Order Status",orderStatus);
        ViewSubsidyRequestsJPanel subsidyStatus=new ViewSubsidyRequestsJPanel(userProcessContainer, userAccount, organization, enterprise, system);
        jTabbedPane.add("Subsidy Status",subsidyStatus);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        requestTestJButton1 = new javax.swing.JButton();
        requestTestJButton2 = new javax.swing.JButton();
        requestTestJButton3 = new javax.swing.JButton();
        jTabbedPane = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(0, 153, 153));

        requestTestJButton.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Request Loan");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });

        enterpriseLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        valueLabel.setFont(new java.awt.Font("Cambria", 0, 12)); // NOI18N
        valueLabel.setText("<value>");

        requestTestJButton1.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        requestTestJButton1.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton1.setText("Order Supplies");
        requestTestJButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton1ActionPerformed(evt);
            }
        });

        requestTestJButton2.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        requestTestJButton2.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton2.setText("Request Subsidy");
        requestTestJButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton2ActionPerformed(evt);
            }
        });

        requestTestJButton3.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton3.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton3.setText("Request Micro Loan");
        requestTestJButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 1009, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(requestTestJButton)
                        .addGap(128, 128, 128)
                        .addComponent(requestTestJButton3)
                        .addGap(241, 241, 241)
                        .addComponent(requestTestJButton1)
                        .addGap(133, 133, 133)
                        .addComponent(requestTestJButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(requestTestJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestTestJButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestBankLoanJPanel", new RequestBankLoanJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void requestTestJButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("OrderSeedJPanel", new OrderSuppliesJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButton1ActionPerformed

    private void requestTestJButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton2ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestSubsidyJPanel", new RequestSubsidyJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButton2ActionPerformed

    private void requestTestJButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButton3ActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestSubsidyJPanel", new RequestMicroLoanJPanel(userProcessContainer, userAccount, enterprise, system));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requestTestJButton3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JButton requestTestJButton1;
    private javax.swing.JButton requestTestJButton2;
    private javax.swing.JButton requestTestJButton3;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
