/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.EnergyRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.MicrofinanceInstitutionEnterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MicroLoanWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.io.File;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.EnergyRole.EnergyWorkAreaJPanel;

/**
 *
 * @author Sanskruti  <your.name at your.org>
 */
public class RequestMicroLoanJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private EcoSystem system;
    /**
     * Creates new form RequestLabTestJPanel
     */
    public RequestMicroLoanJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.system = system;
        valueLabel.setText(enterprise.getName());
        nameJTextField.setText(userAccount.getUsername());
        populateBankComboBox();
    }
    
     private void populateBankComboBox(){
        jComboBox1.removeAllItems();
         for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof MicrofinanceInstitutionEnterprise) {
                    jComboBox1.addItem(enterprise.getName());
                }
             }
        }
    }
     
      private boolean verifyEmailId(String email){
         Pattern p = Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE);
        Matcher m = p.matcher(email);
        boolean b = m.matches();
        return b;
     }
     
      private boolean verifyPhoneNumber(String phone){
         Pattern p = Pattern.compile("[0-9]{10,10}");
        Matcher m = p.matcher(phone);
        boolean b = m.matches();
        return b;
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestTestJButton = new javax.swing.JButton();
        backJButton = new javax.swing.JButton();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ageJTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        addressJTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loanAmountJTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        emailIdJTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        phoneNoJTextField1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ssnPathJTextField = new javax.swing.JTextField();
        panUploadjButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        messageJTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        requestTestJButton.setBackground(new java.awt.Color(0, 0, 0));
        requestTestJButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestJButton.setText("Request Micro-Loan");
        requestTestJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestJButtonActionPerformed(evt);
            }
        });
        add(requestTestJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 570, 180, 40));

        backJButton.setBackground(new java.awt.Color(0, 0, 0));
        backJButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        backJButton.setForeground(new java.awt.Color(255, 255, 255));
        backJButton.setText("<<Back");
        backJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backJButtonActionPerformed(evt);
            }
        });
        add(backJButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 643, 100, 40));

        valueLabel.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 100, -1));

        enterpriseLabel.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(255, 255, 255));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 120, 30));

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        nameJTextField.setEditable(false);
        nameJTextField.setBackground(new java.awt.Color(102, 102, 102));
        nameJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        nameJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(nameJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 150, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Age");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        ageJTextField.setBackground(new java.awt.Color(102, 102, 102));
        ageJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        ageJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(ageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 150, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        addressJTextField.setBackground(new java.awt.Color(102, 102, 102));
        addressJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        addressJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(addressJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 150, -1));

        jLabel5.setBackground(new java.awt.Color(102, 102, 102));
        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Microfinance Name");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Loan Amount");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, -1, -1));

        loanAmountJTextField.setBackground(new java.awt.Color(102, 102, 102));
        loanAmountJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        loanAmountJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(loanAmountJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 250, 150, -1));

        jLabel12.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email Id");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, -1, -1));

        emailIdJTextField.setBackground(new java.awt.Color(102, 102, 102));
        emailIdJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        emailIdJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(emailIdJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 150, -1));

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone No.");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, -1, -1));

        phoneNoJTextField1.setBackground(new java.awt.Color(102, 102, 102));
        phoneNoJTextField1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        phoneNoJTextField1.setForeground(new java.awt.Color(255, 255, 255));
        add(phoneNoJTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 150, -1));

        jLabel8.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SSN Proof");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, -1, -1));

        ssnPathJTextField.setEditable(false);
        ssnPathJTextField.setBackground(new java.awt.Color(102, 102, 102));
        ssnPathJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(ssnPathJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 480, 150, -1));

        panUploadjButton.setBackground(new java.awt.Color(0, 0, 0));
        panUploadjButton.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        panUploadjButton.setForeground(new java.awt.Color(255, 255, 255));
        panUploadjButton.setText("Upload");
        panUploadjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                panUploadjButtonActionPerformed(evt);
            }
        });
        add(panUploadjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 480, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(102, 102, 102));
        jComboBox1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 210, 150, -1));

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Message");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 300, -1, -1));

        messageJTextField.setBackground(new java.awt.Color(102, 102, 102));
        messageJTextField.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        messageJTextField.setForeground(new java.awt.Color(255, 255, 255));
        add(messageJTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 150, -1));

        jLabel9.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("View details");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 50, 230, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/microfinance.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 900));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestJButtonActionPerformed
        
        
        String address = addressJTextField.getText();
        String bankName = (String)jComboBox1.getSelectedItem();
        String emailId = emailIdJTextField.getText();
        String fn=ssnPathJTextField.getText();
        String message = messageJTextField.getText();
        String name = nameJTextField.getText();
        
        if(address.equals("")||bankName.equals("")||emailId.equals(""))
        {
             JOptionPane.showMessageDialog(null, "EmailId, Address are mandatory");
            return;
        }
        
        int age=0;
        
        try{
               age = Integer.parseInt(ageJTextField.getText());
            }
            catch(NumberFormatException e)           
                { JOptionPane.showMessageDialog(null,"Please enter number for age");
                return;
            }
        
        int loanAmount = 0;
        try{
               loanAmount = Integer.parseInt(loanAmountJTextField.getText());
            }
            catch(NumberFormatException e)           
                { JOptionPane.showMessageDialog(null,"Please enter number for Loan Amount");
                return;
            }
        
        if(!verifyEmailId(emailId)){
             JOptionPane.showMessageDialog(null,"Please enter proper email id","ERROR",JOptionPane.ERROR_MESSAGE);
             return;
        }
        long phoneNo=0;
        try{
               phoneNo = Long.parseLong(phoneNoJTextField1.getText());
            }
            catch(NumberFormatException e)           
                { JOptionPane.showMessageDialog(null,"Please enter number for Phone Number");
                return;
            }
        if(!verifyPhoneNumber(phoneNoJTextField1.getText())){
             JOptionPane.showMessageDialog(null,"Please enter proper phone number","ERROR",JOptionPane.ERROR_MESSAGE);
             return;
        } 
        
        MicroLoanWorkRequest request = new MicroLoanWorkRequest();
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setAge(age);
        request.setAddress(address);
        request.setBankName(bankName);
        request.setEmailId(emailId);
        request.setPhoneNo(phoneNo);
        request.setMessage(message);
        request.setLoanAmount(loanAmount);
        request.setName(name);
        
        if(!fn.isEmpty())
        {
        if(fn.endsWith(".pdf")||fn.endsWith(".docx"))
        {
           request.setSsnPath(fn);
        }
         else
           JOptionPane.showMessageDialog(null,"Please upload the Id in correct format","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else
        JOptionPane.showMessageDialog(null,"Please upload the Id","ERROR",JOptionPane.ERROR_MESSAGE);
        
        
        Organization org = null;
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if(enterprise.getName().equalsIgnoreCase(bankName)){
                if (enterprise instanceof MicrofinanceInstitutionEnterprise) {
                            org = enterprise;
                            //                            System.out.println("orgname" + organization.getName());
                            org.getWorkQueue().getWorkRequestList().add(request);
                            userAccount.getWorkQueue().getWorkRequestList().add(request);
                            break;
                       
                }

            }}
        }
        JOptionPane.showMessageDialog(null,"Successfully applied for micro loan","INFO",JOptionPane.INFORMATION_MESSAGE);
        backJButtonActionPerformed(evt);
    }//GEN-LAST:event_requestTestJButtonActionPerformed

    private void backJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backJButtonActionPerformed
        
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        EnergyWorkAreaJPanel dwjp = (EnergyWorkAreaJPanel) component;
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
        
    }//GEN-LAST:event_backJButtonActionPerformed

    private void panUploadjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_panUploadjButtonActionPerformed
        // TODO add your handling code here:
        JFileChooser jc=new JFileChooser();
        jc.showOpenDialog(null);
        File f=jc.getSelectedFile();
        String filename=f.getAbsolutePath();
        ssnPathJTextField.setText(filename);
    }//GEN-LAST:event_panUploadjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressJTextField;
    private javax.swing.JTextField ageJTextField;
    private javax.swing.JButton backJButton;
    private javax.swing.JTextField emailIdJTextField;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField loanAmountJTextField;
    private javax.swing.JTextField messageJTextField;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JButton panUploadjButton;
    private javax.swing.JTextField phoneNoJTextField1;
    private javax.swing.JButton requestTestJButton;
    private javax.swing.JTextField ssnPathJTextField;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}


